name = "highest"
main = "src/worker.js"
compatibility_date = "2024-08-15"

# Uncomment and set your account and routes when deploying
# account_id = "YOUR_ACCOUNT_ID"
# routes = [
#   { pattern = "api.your-domain.com/api/*", zone_name = "your-domain.com" }
# ]

[vars]
# Toggle mock mode for testing without upstream calls
MOCK_AI = "0"
